### ISSUE TITLE
Error while setting up platform eufyrobovac

### ISSUE THREAD

**Issue by FFV21** [BnMcG/HomeAssistant-RoboVac#2]
Hi,

I'm getting the below error and I'm not sure how to fix it.
Any ideas? Thanks in advance!

v 0.93.2
Robovac 15c

```
Error while setting up platform eufyrobovac

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/eufyrobovac/vacuum.py", line 49, in async_setup_platform
    local_code = get_local_code(eufy_username, eufy_password, ip_address)
  File "/config/deps/lib/python3.7/site-packages/robovac/robovac.py", line 48, in get_local_code
    raise EufyApiError('Cannot find local code for device with given IP address. Check that the IP address is correct.')
robovac.robovac.EufyApiError: Cannot find local code for device with given IP address. Check that the IP address is correct.
```

The IP address in the configuration file 100% correct.

**Comment by BnMcG** [comment]
Hi,

Can you post your configuration?

**Comment by FFV21** [comment]
Hi,

I added the below to my configuration.yaml;

```
vacuum:
  - platform: eufyrobovac
    name: RobotVacuum
    ip_address: 192.168.1.58
    username: xxxxxx
    password: xxxxxx
```

Thanks

**Comment by BnMcG** [comment]
Can you confirm you're using the latest version of the component from GitHub? This error is raised when no device matching the IP address given is found while looping through the devices from the Eufy API - if you're sure the IP is correct I'm stumped, as separate errors would be raised if you couldn't authenticate against the API, or if devices couldn't be listed for some other reason.

What version of Python are you using?

**Comment by FFV21** [comment]
I'm using the latest version of the component from GitHub indeed.

I was looking at the documentation here; https://www.home-assistant.io/components/eufy/ and the Eufy API is returning "lan_ip_addr" as my public IP address rather the device's local IP address..
I'm assuming that is what is causing the issue?

**Comment by codypet** [comment]
I see you have Python 3.7.  Could this be related to the issue I had using Python 3.5?

**Comment by BnMcG** [comment]
@FFV21 Yeah, I'd need to double check that's the same endpoint but if it's returning your public IP rather than the LAN IP that'd be the problem... I'm not sure why it would return your public IP if it's the same endpoint, though. 

I don't think just swapping the IP in your config to your public IP would fix the problem, as that's also the IP the component uses to communicate with the vacuum, but I guess it's worth a try as it's not too much effort to try out.

**Comment by FFV21** [comment]
Hi, no I tried using my public IP in the config file but unfortunately that returns the below error;
```
Error while setting up platform eufyrobovac
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/eufyrobovac/vacuum.py", line 58, in async_setup_platform
    await hass.async_add_job(eufy_robovac.connect)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/deps/lib/python3.7/site-packages/robovac/robovac.py", line 153, in connect
    self.s.connect((self.ip, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by BnMcG** [comment]
@FFV21 That's about what I expected but it was worth a try. I'll try and take a look into this in the next couple of days.

**Comment by bionicdude** [comment]
if i modify the code to show the ip address it's checking for
```
for item in devices_from_api['items']:
        if 'device' in item:
            mydevice=item['device']['wifi']['lan_ip_addr']
            if 'device' in item and item['device']['wifi']['lan_ip_addr'] == ip_address:
                return item['device']['local_code']

    raise EufyApiError(mydevice + ' Cannot find local code for device with given IP address. Check that the IP address is correct.')
```
I can see:
`robovac.robovac.EufyApiError: 82.18.xxx.xxx Cannot find local code for device with given IP address. Check that the IP address is correct.`

This is my external address. so looks like the api is putting my external address in the lan_ip_addr part of the return json

EDIT:i hard coded the internal ip of the vacuum and then i get a connection refused error (192.168.XXX.XXX:55556)
EDIT: I just noticed the OP has a 15C. Mine is an 30C (i'm assuming that will make no difference, but thought i'd better mention it).

**Comment by BnMcG** [comment]
@bionicdude This component was written against the 11c's API - I think the 30 series has a different API entirely, and there's a separate Home Assistant component / Python library floating around for it. You can confirm this by checking whether port 55556 is open on the device using a tool like nmap - from the error you received when you hard-coded the IP it sounds like this isn't the case.

**Comment by bionicdude** [comment]
Ah - thanks for that, Ben. I almost didn't mention it as i assumed they'd share a common API. I'm glad i did then. I'll go look for a 30C specific implementation. Good luck with this.
